add karaoke mode via #INSTRUMENTALS or #KARAOKE tag, key to toggle karaoke mode is K while playing.
UltraStar-Deluxe/USDX pull request #850
Opened 2024-05-20 12:46 UTC by dgruss

add karaoke mode via #INSTRUMENTALS or #KARAOKE tag, key to toggle
karaoke mode is K while playing.

2024-05-20 12:54 UTC, bohning commented on game/config.ini
Do not commit your config.ini

2024-05-20 12:55 UTC, bohning commented on game/languages/English.ini
This needs to be added to all translation files.

2024-05-20 12:55 UTC, bohning commented on src/base/USong.pas
> +      else if (Identifier = 'INSTRUMENTALS') or (Identifier = 'KARAOKE') then
The identifier is INSTRUMENTAL, see https://usdx.eu/format/.

2024-05-20 13:07 UTC, dgruss commented
I was not sure what counts on that page as it also lists

> #INSTRUMENTALS: Artist - Title of the song [INSTR].mp3

2024-05-20 16:49 UTC, dgruss commented on game/languages/English.ini
This part is not translated in any language. If you press tab in German, for instance, it's all English.

2024-05-20 16:58 UTC, dgruss commented
changed it to #INSTRUMENTAL only @bohning, config is reset, language - the help is not translated for any language, so I'd keep that as is for now

2024-06-09 15:26 UTC, dgruss commented
anything still to do here?

2024-06-09 16:42 UTC, bohning commented
Not from my side. I think @barbeque-squared hasn't had time to review and merge it.

2024-06-09 16:53 UTC, dgruss commented
actually found one more subtle bug while testing this a bit more (mp3 tag after karaoke tag overwrote the karaoke tag)

2024-06-09 18:02 UTC, dgruss commented
and another one found while playing 😇

2024-07-18 20:27 UTC, bohning commented
So this toggles the use of the normal audio (#MP3) and the instrumental version (#INSTRUMENTAL), right? I just learned that Melody Mania has implemented a slider where you can set the amount of vocals from 0 % (pure karaoke) to 100 % (pure sing-along. Of course that's quite a bit harder to implement, but that would be awesome.
![image](https://github.com/user-attachments/assets/c892bdf8-b11b-47a4-b2b6-91804eddcac6)

2024-07-21 14:24 UTC, barbeque-squared commented
I was testing this branch but could not get it to work. I suspect it's due to a merge conflict from some other change, git is giving me
```
$ git apply 850.diff
error: patch failed: src/screens/UScreenEditSub.pas:4933
error: src/screens/UScreenEditSub.pas: patch does not apply
```

But before that (probably 46cf3f1) it _did_ apply the diff but gave me EAccessViolation when starting a song. It just shows me the video or the background image for a fraction of a second, then crashes. Without this patch it works fine, so I've ruled out config.ini at this point.

what bohning mentions should probably be more of a stretch goal, though shorter-time we can do what we do with `A`: just cycle through a few predefined presets (ie full mp3, full karaoke, 50/50) (but as a follow-up PR please)?

2024-07-21 14:26 UTC, dgruss commented
That's quite odd. I've used this one on several occasions already over multiple hours without a crash. Not sure what might cause this? I can try to see what it does on the most recent version.

2024-07-21 14:59 UTC, barbeque-squared commented on game/config.ini
Ideally config.ini never shows up in these commits at all (rewrite history/force push is fine on branches). I could allow it because this is a relatively small PR should it get merged with squashing enabled, but it would set precedent and now the Piano mode PR also wants in this way, and then someone submits a 1500-line _net_ PR across 3 useful commits but it also changes+undoes line ending changes on everything in src/lib, and well, you can see where this is going.

In general I don't like squashing because it loses information, and I've had way too many times (not on USDX) where a big PR got squashed because "rewriting was too much effort" and then 5 years later it's pinpointed that "somewhere" in there a bug was introduced.

Ideally this PR gets reworked.

2024-07-21 16:10 UTC, DeinAlptraum commented
The crash was my fault, fix PR is open in #874. This only occurs after `./autogen.sh`ing again

2024-07-21 17:24 UTC, barbeque-squared commented
Took me a while to remember `./configure --enable-debug` so it prints stacktraces instead of only "Access violation", but with that I get this output:

```
Exception class: EAccessViolation
Message: Access violation
  $00000000004E2C4E  APPEND,  line 796 of base/UPath.pas
  $0000000000519C93  ONSHOWFINISH,  line 865 of screens/controllers/UScreenSingController.pas
  $000000000045FF0F  DRAW,  line 448 of menu/UDisplay.pas
  $000000000047A3D2  MAINLOOP,  line 344 of base/UMain.pas
  $000000000047A166  MAIN,  line 269 of base/UMain.pas
  $0000000000407487  main,  line 414 of ultrastardx.dpr
```
**This only happens on songs that DO NOT have the #INSTRUMENTAL tag!** Songs that have it are indeed fine, but it's an optional tag. 865 is the AudioPlayback.Open call. I'm assuming CurrentSong.Karaoke is `nil` there (which it should be if the song doesn't have it!) but it's basically getting passed a folder now or something.

2024-07-21 19:24 UTC, dgruss commented
Ah, yes that's possible. I don't have any in my library without the tag.
I'll fix that this week.


Cheers,
Daniel

On 21.07.2024 19:25, barbeque-squared wrote:
> Took me a while to remember |./configure --enable-debug| so it prints 
> stacktraces instead of only "Access violation", but with that I get this 
> output:
> 
> |Exception class: EAccessViolation Message: Access violation 
> $00000000004E2C4E APPEND, line 796 of base/UPath.pas $0000000000519C93 
> ONSHOWFINISH, line 865 of screens/controllers/UScreenSingController.pas 
> $000000000045FF0F DRAW, line 448 of menu/UDisplay.pas $000000000047A3D2 
> MAINLOOP, line 344 of base/UMain.pas $000000000047A166 MAIN, line 269 of 
> base/UMain.pas $0000000000407487 main, line 414 of ultrastardx.dpr |
> 
> *This only happens on songs that DO NOT have the #INSTRUMENTAL tag!* 
> Songs that have it are indeed fine, but it's an optional tag. 865 is the 
> AudioPlayback.Open call. I'm assuming CurrentSong.Karaoke is |nil| there 
> (which it should be if the song doesn't have it!) but it's basically 
> getting passed a folder now or something.
> 
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/UltraStar-Deluxe/USDX/pull/850#issuecomment-2241719233>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAN2M6UQAVGZO2RZW76ECXLZNPVHBAVCNFSM6AAAAABH7VDESGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDENBRG4YTSMRTGM>.
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>
>

2024-07-25 00:41 UTC, dgruss commented
alright. fixed the bug, rebased to new master and squashed the commits

2024-07-29 19:17 UTC, dgruss commented on src/base/USong.pas
> +          if (not Assigned(self.Karaoke)) or (self.Karaoke = PATH_NONE()) then
bugfix was here to also check for not Assigned --> to make sure both .Mp3 and .Karaoke members are initialized to an actual audio file

2025-05-11 16:29 UTC, dgruss commented
it's about a year... how do we proceed?

2025-05-12 21:03 UTC, dgruss commented
tested with files with and without instrumental

2025-05-18 07:26 UTC, barbeque-squared requested changes
Tested this, also with instances where the instrumental is much shorter than the actual song, as well as the other way around. In the former case, once it reaches the end of the instrumental, skipping back with Ctrl^ArrowLeft will not play instrumental anymore, but if anyone has a problem with that, they're welcome to submit a PR that fixes it, because it doesn't crash anything and this is edge case territory I really don't care about.

Aside from the other comment about log statements, there is one other issue that does need to be addressed before this can be merged:

How to reproduce:
* prepare a txt with #AUDIO and #INSTRUMENTAL
* press E to get into the editor
* press S to save

The #INSTRUMENTAL tag isn't getting saved. There should be a save function somewhere, you can most likely leech from how it's handling things like #BACKGROUND, #COVER or #VIDEO (since they're all optional).

`K` itself works fine and the way it toggles (and resets back to audio on the next song) is also fine.

2025-05-18 07:26 UTC, barbeque-squared commented on src/media/UAudioPlaybackBase.pas
> +    Log.LogStatus('Music now at zero!!!', 'TAudioPlayback_Base.ToggleKaraoke');
Are these log statements necessary? (the second one is a few lines down). It's not the end of the world if you want to leave them in, but then at least take out the exclamation marks. Maybe even change it into a `LogDebug` as well but that's up to you, this does have a use if the instrumental is shorter.

2025-05-18 07:35 UTC, dgruss commented
Yes, I would assume that you use identical length versions. Also if the song starts with a 2 minute vocal solo, there would have to be silence padding. It's consistent to expect this at the end as well. Am 18.05.2025 09:26 schrieb barbeque-squared ***@***.***>:
@barbeque-squared requested changes on this pull request.

Tested this, also with instances where the instrumental is much shorter than the actual song, as well as the other way around. In the former case, once it reaches the end of the instrumental, skipping back with Ctrl^ArrowLeft will not play instrumental anymore, but if anyone has a problem with that, they're welcome to submit a PR that fixes it, because it doesn't crash anything and this is edge case territory I really don't care about.
Aside from the other comment about log statements, there is one other issue that does need to be addressed before this can be merged:
How to reproduce:
prepare a txt with #AUDIO and #INSTRUMENTALpress E to get into the editorpress S to save
The #INSTRUMENTAL tag isn't getting saved. There should be a save function somewhere, you can most likely leech from how it's handling things like #BACKGROUND, #COVER or #VIDEO (since they're all optional).
K itself works fine and the way it toggles (and resets back to audio on the next song) is also fine.

In src/media/UAudioPlaybackBase.pas:
>  end;
 
 procedure TAudioPlaybackBase.Pause;
 begin
   if assigned(MusicStream) then
     MusicStream.Pause();
+  if assigned(KaraokeMusicStream) then
+    KaraokeMusicStream.Pause();
+end;
+
+procedure TAudioPlaybackBase.ToggleKaraoke;
+begin
+  KaraokeMode := not KaraokeMode;
+  if KaraokeMode and assigned(KaraokeMusicStream) and assigned(MusicStream) then begin
+    KaraokeMusicStream.Volume := MusicStream.Volume;
+    MusicStream.Volume := 0;
+    Log.LogStatus('Music now at zero!!!', 'TAudioPlayback_Base.ToggleKaraoke');

Are these log statements necessary? (the second one is a few lines down). It's not the end of the world if you want to leave them in, but then at least take out the exclamation marks. Maybe even change it into a LogDebug as well but that's up to you, this does have a use if the instrumental is shorter.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2025-05-18 07:48 UTC, dgruss commented on src/media/UAudioPlaybackBase.pas
> +    Log.LogStatus('Music now at zero!!!', 'TAudioPlayback_Base.ToggleKaraoke');
will remove the log statements

2025-05-18 07:53 UTC, dgruss commented
fixed the file save bug and removed the comments @barbeque-squared

2025-05-18 08:03 UTC, barbeque-squared approved these changes
Can confirm it works now. Thank you for the contribution! I'll merge once I figure out if the failing Windows job is just a fluke, consistently broken but unrelated to this PR, or (somehow) this PR breaking it.

EDIT: retried the job and it worked fine, so it's merged

2025-05-18 08:05 UTC, merged