Have TLua_CustomRequire put the module table on the Lua stack.
UltraStar-Deluxe/USDX pull request #854
Opened 2024-06-02 12:02 UTC by hoehermann

As it is the custom since Lua 5.2, see http://lua-users.org/wiki/CompatibilityWithLuaFive.

2024-07-13 14:10 UTC, barbeque-squared requested changes
This PR breaks my own (non-party) plugins. Reproducible on Linux with attached file [logsongs.txt](https://github.com/user-attachments/files/16202398/logsongs.txt):
1. Rename it to `logsongs.usdx` and put it in the plugins folder
2. `touch /tmp/usdxfifologsongs` (the plugin only runs if this file exists, you can change it at the top of the plugin)
3. Start USDX
4. Go to Sing, start any song and get to the score screen (escaping the song is fine)

Expected result: it adds two lines to the file, eg:
```
{"artist":"Wolfcora Zebry","title":"Böse Stuten (dev version)","event":"start"}
{"complete":false,"event":"end"}
```

Actual result:
As soon as USDX starts it starts spamming
`ERROR:  /home/bbq/gits/Ultrastar/USDX/game/plugins/logsongs.usdx:41: attempt to call a nil value (field 'GetCurrentScreen') [lua/Log songs API]`
over and over and over and over in Error.log

I don't know what I would need to edit in my plugin to get it working again. I'm aware that what I'm doing _probably_ isn't quite what plugins were originally meant for, and since this PR doesn't (appear to) break the shipped party plugins, I'm willing to merge if my type of plugin can be fixed. I use this and more sophisticated variants in production.

2024-07-13 14:17 UTC, barbeque-squared commented
UPDATE: it's also erroring on the base branch, either my environment is off or there's something custom somewhere where it's not supposed to be

2024-07-13 14:27 UTC, barbeque-squared approved these changes

2024-07-13 14:27 UTC, merged

2024-07-14 13:08 UTC, hoehermann commented
Thank you very much. ♥