Use P1 inverted color to mark selected bar in editor
UltraStar-Deluxe/USDX pull request #870
Opened 2024-07-14 18:08 UTC by DeinAlptraum

Before, the selected bar would use P2's color to mark the selected bar. This leads to no marking at all when no color has been selected for P2.

The color attribute for each bar currently holds only a single integer for the player number, since this reuses the coloring-mechanism of the actual sing mode. I chose to mark the selected syllable as belonging to player 99 (instead of player 2) and then making a distinction for that number. The choice is arbitrary, I just didn't want to use 0 since it seems to be already used for something else.

Currently, the color used for marking is the inversion of P1's color. We could also change this to not be based on the player colors at all, and instead use two fixed colors for selected/not selecte or similar.

2024-07-18 06:49 UTC, barbeque-squared requested changes
I'm fine with hardcoding/(ab)using 99 to be this color (otherwise it's probably going to explode in PR size) however I would request the following changes:

* define a constant eg `INVERTED_1 = 99` in UDraw (use a better name if you have one)
* Use that constant instead of hardcoding 99 in UDraw and UScreenEditSub

makes things more self-explanatory when someone looks at this code in a year's time or so.

2024-07-18 10:38 UTC, DeinAlptraum commented
That's a good idea, changed

2024-07-18 15:07 UTC, barbeque-squared commented on src/screens/views/UScreenSingView.pas
> +  Tex_Left_Rap_Inv := Texture.LoadTexture(Skin.GetTextureFileName('GrayLeftRap'), TEXTURE_TYPE_COLORIZED, Color);
If I apply the patch I get this warning:
```
$ git apply 870.patch
870.patch:286: trailing whitespace.
  Tex_Left_Rap_Inv := Texture.LoadTexture(Skin.GetTextureFileName('GrayLeftRap'), TEXTURE_TYPE_COLORIZED, Color); 
warning: 1 line adds whitespace errors.
```

Not really an issue, but I tend to try not to introduce these in new code (exactly because of the above command, git does that by default). Though if we want to enforce this, there should probably be some kind of CI thing that detects them (if only changed is too hard, can also just run on the entire code base, we can just do a single pass to clean up or something).

I also noticed that when editing a duet it still uses the P2 color* when you switch to the other player (Alt+Up/Down iirc), but once you start navigating notes/sentences it switches to the inverted P1 color. Not the biggest deal since it's also using the P2 color* for the P2 sentence bar thing.\
\* = I THINK. Could also be the randomly selected color if you only have 1 player again, didn't test enough to know for sure.

Up to you if you want to fix either, the first isn't enforced (yet?), the second is duet only so we're already down to <3% of all songs or so.

2024-07-18 15:22 UTC, DeinAlptraum commented on src/screens/views/UScreenSingView.pas
> +  Tex_Left_Rap_Inv := Texture.LoadTexture(Skin.GetTextureFileName('GrayLeftRap'), TEXTURE_TYPE_COLORIZED, Color);
Fixed the whitespace and the color change for track changing on duet songs.

2024-07-21 12:40 UTC, barbeque-squared approved these changes

2024-07-21 13:33 UTC, barbeque-squared commented
Took me a while to realize that `870.patch` is not the same as `870.diff`. Which makes sense I guess.
And the duet stuff is now also consistent, very nice, thanks!

I've opened #873 to keep track of the whitespace.

2024-07-21 13:33 UTC, merged